apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    customer: govanin
spec:
  template:
    metadata:
      name: my-pod
      labels:
        type: web
        customer: govanin
    spec:
      containers:
       - name: nginx
         image: nginx
  replicas: 3
